### ISSUE TITLE
Qt Dependencies

### ISSUE THREAD

**Issue by 3YmY6X** [MarianArlt/kde-plasmoid-inlineclock#5]
Nothing shows up when I add the widget but I'm able to right-click the blank space and go to your widget settings where I'm met with the following error:

`Error: Could not load: file:///home/user/.local/share/plasma/plasmoids/org.kde.plasma.inlineClock/contents/ui/configAppearance.qml:24 module "QtQuickControls" version 2.3 is not installed`

Based on that, I assume I'm missing some dependency but I'm not quite sure how to go about getting it.

**Comment by melihozbek** [comment]
I have the same exact issue with Qt dependencies!

**Comment by MarianArlt** [comment]
Hmmm. What's your guys `Qt5` base package version and your distro? `QtQuickControls` version 2.3 requires `Qt5` 5.10 or higher.
My suggestion would be to see if you can install the latest versions of the following packages (Arch):
`qt5-base` `qt5-quickcontrols` `qt5-quickcontrol2` they should be 5.12 or 5.12.x (depending on your distro).

**Comment by melihozbek** [comment]
I see, thanks for your response. I'm using KDE plasma 5.12, with 18.04 LTS. The three packages you mentioned, I can't find in repositories. But `apt list --installed |grep qt5` gives

`libqt5quickcontrols2-5/bionic,now 5.9.5-0ubuntu2 amd64 [installed]`

**Comment by melihozbek** [comment]
Ah, I think I got it. I got 5.9.X, but I guess you're saying I need 5.10 and higher :)
 `~ > kf5-config --version
Qt: 5.9.5
KDE Frameworks: 5.47.0
kf5-config: 1.0
~ > 
`

**Comment by MarianArlt** [comment]
Yes indeed. Thanks for coming back and commenting.

**Comment by KevinEsh** [comment]
@melihozbek how can I install 5.10 or higher? I'm having the same issue with the same distro

**Comment by MarianArlt** [comment]
Kevin, if you're on any distribution version that is LTS (Long Term Support) you should *not* update individual system components! Your system might break. This is not to say it's impossible, but it requires a level of attention that is unreasonable for most things. You may ask in your distro's forum for more information. I highly advise against it.
